var initialUserState = {
	data: [
		{
			"_class": "course",
			"id": 625204,
			"title": "The Web Developer Bootcamp",
			"url": "/the-web-developer-bootcamp/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/coltsteele/",
					"display_name": "Colt Steele",
					"id": 4466306,
					"initials": "CS",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/4466306_6fd8_2.jpg",
					"title": "Colt Steele",
					"job_title": "Developer and Bootcamp Instructor",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/4466306_6fd8_2.jpg",
					"name": "Colt"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/625204_436a_2.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/625204_436a_2.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/625204_436a_2.jpg",
			"published_title": "the-web-developer-bootcamp",
			"headline": "The only course you need to learn web development - HTML, CSS, JS, Node, and More!",
			"num_subscribers": 169113,
			"avg_rating": 4.73593,
			"avg_rating_recent": 4.722203317737133,
			"num_reviews": 40429,
			"is_wishlisted": false,
			"num_published_lectures": 345,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/625204_436a_2.jpg",
			"locale": {
				"locale": "en_US",
				"english_title": "English (US)",
				"title": "English (US)",
				"_class": "locale"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2015-11-02T21:13:27Z",
			"objectives_summary": [
				"Make REAL web applications using cutting-edge technologies",
				"Continue to learn and grow as a developer, long after the course ends",
				"Create a blog application from scratch using Express, MongoDB, and Semantic UI"
			],
			"bestseller_badge_content": {
				"badge_text": "Best Seller",
				"context_info": null,
				"topic_info": {
					"url": "/topic/web-development/",
					"title": "Web Development Fundamentals"
				}
			},
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/625204/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "43 hours"
		},
		{
			"_class": "course",
			"id": 567828,
			"title": "Complete Python Bootcamp: Go from zero to hero in Python",
			"url": "/complete-python-bootcamp/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/joseporitlla/",
					"display_name": "Jose Portilla",
					"id": 9685726,
					"initials": "JP",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/9685726_67e7_2.jpg",
					"title": "Jose Portilla",
					"job_title": "Data Scientist",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/9685726_67e7_2.jpg",
					"name": "Jose"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/567828_67d0.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/567828_67d0.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/567828_67d0.jpg",
			"published_title": "complete-python-bootcamp",
			"headline": "Learn Python like a Professional! Start from the basics and go all the way to creating your own applications and games!",
			"num_subscribers": 159634,
			"avg_rating": 4.51636,
			"avg_rating_recent": 4.49773853112212,
			"num_reviews": 29250,
			"is_wishlisted": false,
			"num_published_lectures": 113,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/567828_67d0.jpg",
			"locale": {
				"locale": "en_US",
				"english_title": "English (US)",
				"title": "English (US)",
				"_class": "locale"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2015-10-12T21:42:53Z",
			"objectives_summary": [
				"Learn to use Python professionally, learning both Python 2 and Python 3!",
				"Create games with Python, like Tic Tac Toe and Blackjack!",
				"Learn advanced Python features, like the collections module and how to work with timestamps!"
			],
			"bestseller_badge_content": {
				"badge_text": "Best Seller",
				"context_info": null,
				"topic_info": {
					"url": "/topic/python/",
					"title": "Python"
				}
			},
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/567828/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$200",
			"content_info": "13 hours"
		},
		{
			"_class": "course",
			"id": 533682,
			"title": "Complete Java Masterclass",
			"url": "/java-the-complete-java-developer-course/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/timbuchalka/",
					"display_name": "Tim Buchalka",
					"id": 599932,
					"initials": "TB",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/599932_71aa_2.jpg",
					"title": "Tim Buchalka",
					"job_title": "Java,  Android & Python Expert Developer - 175,000 students!",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/599932_71aa_2.jpg",
					"name": "Tim"
				},
				{
					"url": "/user/jojo-rabbit/",
					"display_name": "Goran Lochert",
					"id": 19087122,
					"initials": "GL",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/19087122_6d0f_2.jpg",
					"title": "Goran Lochert",
					"job_title": "Software Engineer | Udemy Instructor | Indie Game Developer",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/19087122_6d0f_2.jpg",
					"name": "Goran"
				},
				{
					"url": "/user/learn-programming-academy/",
					"display_name": "Tim Buchalka's Learn Programming Academy",
					"id": 35101150,
					"initials": "TP",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/35101150_6f0c_4.jpg",
					"title": "Tim Buchalka's Learn Programming Academy",
					"job_title": "Professional Programmers and Teachers - 175,000+ students",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/35101150_6f0c_4.jpg",
					"name": "Tim Buchalka's Learn"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/533682_c10c_3.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/533682_c10c_3.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/533682_c10c_3.jpg",
			"published_title": "java-the-complete-java-developer-course",
			"headline": "Learn to master Java 8 and Java 9 core development step-by-step, and make your first unique, advanced program in 30 days",
			"num_subscribers": 140406,
			"avg_rating": 4.62412,
			"avg_rating_recent": 4.594555644515612,
			"num_reviews": 26870,
			"is_wishlisted": false,
			"num_published_lectures": 314,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/533682_c10c_3.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2015-07-21T22:01:13Z",
			"objectives_summary": [
				"How to build creative, fully-functional Java 8 programs with confidence (whilst having fun, too)",
				"How to program the right way, cutting out the useless fluff and filler",
				"How to easily write advanced programs for all computing platforms at once"
			],
			"bestseller_badge_content": {
				"badge_text": "Best Seller",
				"context_info": null,
				"topic_info": {
					"url": "/topic/java/",
					"title": "Java"
				}
			},
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/533682/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$200",
			"content_info": "69.5 hours"
		},
		{
			"_class": "course",
			"id": 764164,
			"title": "The Complete Web Developer Course 2.0",
			"url": "/the-complete-web-developer-course-2/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/robpercival/",
					"display_name": "Rob Percival",
					"id": 4387876,
					"initials": "RP",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/4387876_78bc.jpg",
					"title": "Rob Percival",
					"job_title": "Web Developer And Teacher",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/4387876_78bc.jpg",
					"name": "Rob"
				},
				{
					"url": "/user/codestars/",
					"display_name": "Codestars by Rob Percival",
					"id": 33231436,
					"initials": "CB",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/33231436_2824_3.jpg",
					"title": "Codestars by Rob Percival",
					"job_title": "Teaching the Next Generation of Coders",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/33231436_2824_3.jpg",
					"name": "Codestars"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/764164_de03_2.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/764164_de03_2.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/764164_de03_2.jpg",
			"published_title": "the-complete-web-developer-course-2",
			"headline": "Learn Web Development by building 25 websites and mobile apps using HTML, CSS, Javascript, PHP, Python, MySQL & more!",
			"num_subscribers": 133904,
			"avg_rating": 4.656,
			"avg_rating_recent": 4.621290467625899,
			"num_reviews": 27385,
			"is_wishlisted": false,
			"num_published_lectures": 304,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/764164_de03_2.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2016-03-08T22:28:36Z",
			"objectives_summary": [
				"Build websites and webapps",
				"Build HTML-based mobile apps",
				"Get a job as a junior web developer"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/764164/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "30.5 hours"
		},
		{
			"_class": "course",
			"id": 692188,
			"title": "The Python Mega Course: Build 10 Real World Applications",
			"url": "/the-python-mega-course/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/adiune/",
					"display_name": "Ardit Sulce",
					"id": 717783,
					"initials": "AS",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/717783_3157.jpg",
					"title": "Ardit Sulce",
					"job_title": "Python and GIS Expert, Founder of PythonHow.com",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/717783_3157.jpg",
					"name": "Ardit"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/692188_9da7.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/692188_9da7.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/692188_9da7.jpg",
			"published_title": "the-python-mega-course",
			"headline": "The only Python course covering web, databases, web scraping, data science, web visualizations, image processing & more!",
			"num_subscribers": 57309,
			"avg_rating": 4.38388,
			"avg_rating_recent": 4.405526992287918,
			"num_reviews": 9008,
			"is_wishlisted": false,
			"num_published_lectures": 205,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/692188_9da7.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2016-06-08T17:12:30Z",
			"objectives_summary": [
				"Become a Python programmer able to independently develop complex applications in Python 3.",
				"Build 10 real life Python applications in a wide range of areas.",
				"Improve your skills with bonus practice activities throughout the course."
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/692188/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$200",
			"content_info": "24 hours"
		},
		{
			"_class": "course",
			"id": 1289478,
			"title": "iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp",
			"url": "/ios-11-app-development-bootcamp/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/4b4368a3-b5c8-4529-aa65-2056ec31f37e/",
					"display_name": "Angela Yu",
					"id": 31334738,
					"initials": "AY",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/31334738_a13c_2.jpg",
					"title": "Angela Yu",
					"job_title": "iOS Developer and Teacher",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/31334738_a13c_2.jpg",
					"name": "Angela"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1289478_5831_6.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1289478_5831_6.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1289478_5831_6.jpg",
			"published_title": "ios-11-app-development-bootcamp",
			"headline": "Learn iOS 11 App Development From Beginning to End. Using Xcode 9 and Swift 4. Includes Full ARKit and CoreML Modules!",
			"num_subscribers": 18288,
			"avg_rating": 4.77503,
			"avg_rating_recent": 4.7750299760191846,
			"num_reviews": 3336,
			"is_wishlisted": false,
			"num_published_lectures": 393,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1289478_5831_6.jpg",
			"locale": {
				"locale": "en_US",
				"title": "English (US)",
				"_class": "locale",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-07-20T15:11:53Z",
			"objectives_summary": [
				"How to build any app you want",
				"Craft a portfolio of apps to apply for junior developer jobs",
				"Build fully-fledged apps for your startup or business"
			],
			"bestseller_badge_content": {
				"badge_text": "Best Seller",
				"context_info": null,
				"topic_info": {
					"url": "/topic/ios-development/",
					"title": "iOS Development"
				}
			},
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/1289478/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "37 hours"
		},
		{
			"_class": "course",
			"id": 1350282,
			"title": "Kotlin for Java Developers",
			"url": "/kotlin-for-java-developers-q/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/aman-thakur-6/",
					"display_name": "Aman Thakur",
					"id": 24068324,
					"initials": "AT",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/24068324_8211_4.jpg",
					"title": "Aman Thakur",
					"job_title": "Software Developer",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/24068324_8211_4.jpg",
					"name": "Aman"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1350282_914c_9.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1350282_914c_9.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1350282_914c_9.jpg",
			"published_title": "kotlin-for-java-developers-q",
			"headline": "Statically typed programming language for modern multiplatform applications",
			"num_subscribers": 1105,
			"avg_rating": 4.3,
			"avg_rating_recent": 4.3,
			"num_reviews": 5,
			"is_wishlisted": false,
			"num_published_lectures": 25,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1350282_914c_9.jpg",
			"locale": {
				"locale": "en_US",
				"title": "English (US)",
				"_class": "locale",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "Intermediate Level",
			"instructional_level_simple": "Intermediate",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-10-12T19:50:48Z",
			"objectives_summary": [
				"Create Kotlin Projects",
				"Build modern multiplatform applications",
				"Build Android apps using Kotlin Programming"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1350282/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$50",
			"content_info": "1.5 hours"
		},
		{
			"_class": "course",
			"id": 1383496,
			"title": "Server Side Rendering with React and Redux",
			"url": "/server-side-rendering-with-react-and-redux/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/sgslo/",
					"display_name": "Stephen Grider",
					"id": 5487312,
					"initials": "SG",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/5487312_0554.jpg",
					"title": "Stephen Grider",
					"job_title": "Engineering Architect",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/5487312_0554.jpg",
					"name": "Stephen"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1383496_caab_4.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1383496_caab_4.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1383496_caab_4.jpg",
			"published_title": "server-side-rendering-with-react-and-redux",
			"headline": "Build React, Redux, and React Router apps using Server Side Rendering (SSR), Isomorphic, and Universal JS techniques",
			"num_subscribers": 130,
			"avg_rating": 5,
			"avg_rating_recent": 5,
			"num_reviews": 11,
			"is_wishlisted": false,
			"num_published_lectures": 93,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1383496_caab_4.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "Intermediate Level",
			"instructional_level_simple": "Intermediate",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-10-11T04:46:10Z",
			"objectives_summary": [
				"Understand the challenges of Server Side Rendering",
				"Build a server side rendering boilerplate project",
				"Use React, Redux, and React Router to conquer Search Engine Optimization"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1383496/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$45",
			"content_info": "8 hours"
		},
		{
			"_class": "course",
			"id": 1377870,
			"title": "Advanced iOS 11: Mastering Push Notifications",
			"url": "/ios-push-notifications/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/devslopes/",
					"display_name": "Devslopes by Mark Price",
					"id": 33233514,
					"initials": "DB",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/33233514_35d0_3.jpg",
					"title": "Devslopes by Mark Price",
					"job_title": "Learn programming & app development",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/33233514_35d0_3.jpg",
					"name": "Devslopes"
				},
				{
					"url": "/user/5580dd60b209c/",
					"display_name": "Kyle Lee",
					"id": 13554120,
					"initials": "KL",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/13554120_c7b1.jpg",
					"title": "Kyle Lee",
					"job_title": "Swift Developer and Educator",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/13554120_c7b1.jpg",
					"name": "Kyle"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1377870_f445.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1377870_f445.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1377870_f445.jpg",
			"published_title": "ios-push-notifications",
			"headline": "Everything you could ever want to know about push notifications for iOS 11 in Swift",
			"num_subscribers": 286,
			"avg_rating": 4.78571,
			"avg_rating_recent": 4.785714285714286,
			"num_reviews": 7,
			"is_wishlisted": false,
			"num_published_lectures": 48,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1377870_f445.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "Intermediate Level",
			"instructional_level_simple": "Intermediate",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-10-10T18:37:01Z",
			"objectives_summary": [
				"Implement Local Notifications on iOS",
				"Implement push notifications with CloudKit & iCloud",
				"Implement push notifications with AWS"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1377870/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "11.5 hours"
		},
		{
			"_class": "course",
			"id": 1365482,
			"title": "Learn MATLAB and Simulink Programming",
			"url": "/learn-matlab-and-simulink-programming/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/jordanchristman/",
					"display_name": "Jordan Christman",
					"id": 9593581,
					"initials": "JC",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/9593581_3253_2.jpg",
					"title": "Jordan Christman",
					"job_title": "Your FPGA Guy",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/9593581_3253_2.jpg",
					"name": "Jordan"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1365482_21c1.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1365482_21c1.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1365482_21c1.jpg",
			"published_title": "learn-matlab-and-simulink-programming",
			"headline": "Master MATLAB Programming fundamentals and Simulink to increase your number crunching abilities.",
			"num_subscribers": 1617,
			"avg_rating": 4.75,
			"avg_rating_recent": 4.75,
			"num_reviews": 14,
			"is_wishlisted": false,
			"num_published_lectures": 71,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1365482_21c1.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-10-10T00:34:16Z",
			"objectives_summary": [
				"Understand most of the basic MATLAB commmands",
				"Able to build their own Simulink models and simulate them"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1365482/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$75",
			"content_info": "6.5 hours"
		},
		{
			"_class": "course",
			"id": 1382914,
			"title": "Learn Microservices with Spring Boot and Spring Cloud",
			"url": "/learn-microservices-with-spring-boot-and-spring-cloud/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/ledeng/",
					"display_name": "Le Deng",
					"id": 9637384,
					"initials": "LD",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/9637384_6f91_4.jpg",
					"title": "Le Deng",
					"job_title": "ldeng.net/courses, consultant, thousands of students",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/9637384_6f91_4.jpg",
					"name": "Le"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1382914_780a_4.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1382914_780a_4.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1382914_780a_4.jpg",
			"published_title": "learn-microservices-with-spring-boot-and-spring-cloud",
			"headline": "A Hands-on Guide on Spring and Microservices",
			"num_subscribers": 156,
			"avg_rating": 4.45455,
			"avg_rating_recent": 4.454545454545454,
			"num_reviews": 11,
			"is_wishlisted": false,
			"num_published_lectures": 46,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1382914_780a_4.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": false,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-10-09T19:27:27Z",
			"objectives_summary": [
				"Understand what Microservice is",
				"Understand the architecture of Microservice",
				"Know how to build Microservice with Spring"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1382914/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$200",
			"content_info": "10 hours"
		},
		{
			"_class": "course",
			"id": 1359020,
			"title": "Hands on With Docker & Docker Compose From a Docker Captain",
			"url": "/hands-on-with-docker-and-docker-compose/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/nick-janetakis/",
					"display_name": "Nick Janetakis",
					"id": 16148498,
					"initials": "NJ",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/16148498_4280_2.jpg",
					"title": "Nick Janetakis",
					"job_title": "Developer / Docker Captain / Teacher",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/16148498_4280_2.jpg",
					"name": "Nick"
				},
				{
					"url": "/user/docker-captain/",
					"display_name": "Docker Captain Program",
					"id": 29690858,
					"initials": "DP",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/29690858_9e4e_3.jpg",
					"title": "Docker Captain Program",
					"job_title": "",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/29690858_9e4e_3.jpg",
					"name": "Docker Captain"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1359020_5426.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1359020_5426.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1359020_5426.jpg",
			"published_title": "hands-on-with-docker-and-docker-compose",
			"headline": "v17.09. Everything you need to build, run and compose Docker containers so you can start using Docker for your web apps.",
			"num_subscribers": 231,
			"avg_rating": 4.94444,
			"avg_rating_recent": 4.944444444444445,
			"num_reviews": 9,
			"is_wishlisted": false,
			"num_published_lectures": 51,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1359020_5426.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": false,
			"instructional_level": "Beginner Level",
			"instructional_level_simple": "Beginner",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-10-06T18:44:00Z",
			"objectives_summary": [
				"Understand what Docker is and isn't",
				"Install Docker on MacOS, Windows & Linux",
				"Understand Docker's ecosystem"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1359020/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$65",
			"content_info": "4.5 hours"
		},
		{
			"_class": "course",
			"id": 1315842,
			"title": "Comprehensive macOS Development",
			"url": "/comprehensive-macos-development/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/devslopes/",
					"display_name": "Devslopes by Mark Price",
					"id": 33233514,
					"initials": "DB",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/33233514_35d0_3.jpg",
					"title": "Devslopes by Mark Price",
					"job_title": "Learn programming & app development",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/33233514_35d0_3.jpg",
					"name": "Devslopes"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1315842_70b9.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1315842_70b9.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1315842_70b9.jpg",
			"published_title": "comprehensive-macos-development",
			"headline": "Learn basic and advanced macOS development by building a polished, fully functional weather widget app and a chat app!",
			"num_subscribers": 256,
			"avg_rating": 4.78571,
			"avg_rating_recent": 4.785714285714286,
			"num_reviews": 7,
			"is_wishlisted": false,
			"num_published_lectures": 59,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1315842_70b9.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "Intermediate Level",
			"instructional_level_simple": "Intermediate",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-09-21T00:33:00Z",
			"objectives_summary": [
				"Foundational macOS development - learn the basics to advanced topics",
				"How to build a Slack clone - User interface, networking services, and server deployment",
				"macOS Toolbar apps - apps that can run in the background and operate from a toolbar"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1315842/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "16.5 hours"
		},
		{
			"_class": "course",
			"id": 1342418,
			"title": "The Complete JavaScript Course - Beginner to Professional",
			"url": "/javascript-training/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/codestars/",
					"display_name": "Codestars by Rob Percival",
					"id": 33231436,
					"initials": "CB",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/33231436_2824_3.jpg",
					"title": "Codestars by Rob Percival",
					"job_title": "Teaching the Next Generation of Coders",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/33231436_2824_3.jpg",
					"name": "Codestars"
				},
				{
					"url": "/user/lars51/",
					"display_name": "Laurence Svekis",
					"id": 5581552,
					"initials": "LS",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/5581552_b409_14.jpg",
					"title": "Laurence Svekis",
					"job_title": "Instructor, 18+yrs Web Experience",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/5581552_b409_14.jpg",
					"name": "Laurence"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1342418_b2f3_14.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1342418_b2f3_14.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1342418_b2f3_14.jpg",
			"published_title": "javascript-training",
			"headline": "The only course you need to become a JavaScript developer - 45 JavaScript projects, ES6, JSON, AJAX & much more!",
			"num_subscribers": 2477,
			"avg_rating": 4.53922,
			"avg_rating_recent": 4.53921568627451,
			"num_reviews": 51,
			"is_wishlisted": false,
			"num_published_lectures": 387,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1342418_b2f3_14.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-09-25T17:08:20Z",
			"objectives_summary": [
				"Master the #1 programming language in the world",
				"Become a professional JavaScript developer",
				"Build games, web apps and websites in JavaScript"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1342418/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "34.5 hours"
		},
		{
			"_class": "course",
			"id": 14346,
			"title": "Learn C# Programming (In Ten Easy Steps)",
			"url": "/learn-c-sharp-programming-in-ten-easy-steps/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/huwcollingbourne/",
					"display_name": "Huw Collingbourne",
					"id": 35269,
					"initials": "HC",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/35269_e577_5.jpg",
					"title": "Huw Collingbourne",
					"job_title": "Director of Technology, SapphireSteel Software",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/35269_e577_5.jpg",
					"name": "Huw"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/14346_9972_8.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/14346_9972_8.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/14346_9972_8.jpg",
			"published_title": "learn-c-sharp-programming-in-ten-easy-steps",
			"headline": "The simplest way to learn C# programming.",
			"num_subscribers": 2009,
			"avg_rating": 4.25685,
			"avg_rating_recent": 4.364864864864865,
			"num_reviews": 146,
			"is_wishlisted": false,
			"num_published_lectures": 123,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/14346_9972_8.jpg",
			"locale": {
				"locale": "en_US",
				"title": "English (US)",
				"_class": "locale",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "Beginner Level",
			"instructional_level_simple": "Beginner",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2012-03-26T15:30:40Z",
			"objectives_summary": [
				"Master C# programming concepts from the ground up",
				"Use the source code examples to learn step-by-step",
				"Understand the special features of C#: object orientation, the .NET framework, error-handling, serialization"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": false,
			"preview_url": "/14346/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$150",
			"content_info": "7 hours"
		},
		{
			"_class": "course",
			"id": 1319066,
			"title": "Unreal Multiplayer Mastery - Online Game Development In C++",
			"url": "/unrealmultiplayer/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/samuel-pattuzzi/",
					"display_name": "Sam Pattuzzi",
					"id": 16903220,
					"initials": "SP",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/16903220_be08_2.jpg",
					"title": "Sam Pattuzzi",
					"job_title": "Software Engineer, University of Cambridge",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/16903220_be08_2.jpg",
					"name": "Sam"
				},
				{
					"url": "/user/gamedevtv/",
					"display_name": "GameDev.tv by Ben Tristem",
					"id": 33027212,
					"initials": "GB",
					"_class": "user",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/33027212_4271_3.jpg",
					"title": "GameDev.tv by Ben Tristem",
					"job_title": "Learn to Make and Sell Games",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/33027212_4271_3.jpg",
					"name": "GameDev.tv"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1319066_eee6_2.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1319066_eee6_2.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1319066_eee6_2.jpg",
			"published_title": "unrealmultiplayer",
			"headline": "Use Epic's Unreal Engine for online game development in C++. Covers LAN, VPN, Steam, and more.",
			"num_subscribers": 1684,
			"avg_rating": 4.58824,
			"avg_rating_recent": 4.588235294117647,
			"num_reviews": 17,
			"is_wishlisted": false,
			"num_published_lectures": 71,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1319066_eee6_2.jpg",
			"locale": {
				"locale": "en_GB",
				"english_title": "English (UK)",
				"title": "English (UK)",
				"_class": "locale"
			},
			"has_closed_caption": true,
			"instructional_level": "Intermediate Level",
			"instructional_level_simple": "Intermediate",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-09-06T22:31:58Z",
			"objectives_summary": [
				"Build multiplayer games.",
				"Share games with a large audience.",
				"Connect games via the Steam APIs."
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1319066/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$105",
			"content_info": "16 hours"
		},
		{
			"_class": "course",
			"id": 1322294,
			"title": "Devops COMPLETE Guide with Docker + Jenkins + GIT Hands On!",
			"url": "/devops-docker-complete-guide-hands-on-with-practical/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/adhir-kumar-ghosh/",
					"display_name": "Joydip Ghosh Academy",
					"id": 33542376,
					"initials": "JA",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/33542376_5cae_2.jpg",
					"title": "Joydip Ghosh Academy",
					"job_title": "New Skills Everyday!",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/33542376_5cae_2.jpg",
					"name": "Joydip Ghosh"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1322294_c911_5.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1322294_c911_5.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1322294_c911_5.jpg",
			"published_title": "devops-docker-complete-guide-hands-on-with-practical",
			"headline": "Practical Hands On Project Using Docker, Jenkins and Git Technologies",
			"num_subscribers": 9595,
			"avg_rating": 4.52045,
			"avg_rating_recent": 4.5204545454545455,
			"num_reviews": 220,
			"is_wishlisted": false,
			"num_published_lectures": 45,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1322294_c911_5.jpg",
			"locale": {
				"locale": "en_IN",
				"english_title": "English (India)",
				"title": "English (India)",
				"_class": "locale"
			},
			"has_closed_caption": true,
			"instructional_level": "All Levels",
			"instructional_level_simple": "All",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-08-18T21:42:38Z",
			"objectives_summary": [
				"Real life Hands On Training on docker!"
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1322294/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$25",
			"content_info": "6 hours"
		},
		{
			"_class": "course",
			"id": 1354196,
			"title": "Complete Unity and Android Development: Build Games and Apps",
			"url": "/complete-unity-and-android-development-build-games-and-apps/",
			"is_paid": true,
			"visible_instructors": [
				{
					"url": "/user/mammoth-interactive/",
					"display_name": "Mammoth Interactive",
					"id": 22923344,
					"initials": "MI",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/22923344_6365_4.jpg",
					"title": "Mammoth Interactive",
					"job_title": "Best selling course provider since 2011!",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/22923344_6365_4.jpg",
					"name": "Mammoth"
				},
				{
					"url": "/user/johnbura/",
					"display_name": "John Bura",
					"id": 55737,
					"initials": "JB",
					"_class": "user",
					"image_50x50": "https://udemy-images.udemy.com/user/50x50/55737_2d11_5.jpg",
					"title": "John Bura",
					"job_title": "Best Selling Instructor Web/App/Game Developer 300k Students",
					"image_100x100": "https://udemy-images.udemy.com/user/100x100/55737_2d11_5.jpg",
					"name": "John"
				}
			],
			"image_125_H": "https://udemy-images.udemy.com/course/125_H/1354196_6a7e.jpg",
			"image_240x135": "https://udemy-images.udemy.com/course/240x135/1354196_6a7e.jpg",
			"is_practice_test_course": false,
			"image_480x270": "https://udemy-images.udemy.com/course/480x270/1354196_6a7e.jpg",
			"published_title": "complete-unity-and-android-development-build-games-and-apps",
			"headline": "Learn to code and build beginner Android apps! Build a Legend of Zenda game in Unity3D. Make unique game art in Blender.",
			"num_subscribers": 57,
			"avg_rating": 4.5,
			"avg_rating_recent": 4.5,
			"num_reviews": 3,
			"is_wishlisted": false,
			"num_published_lectures": 393,
			"num_published_practice_tests": 0,
			"image_304x171": "https://udemy-images.udemy.com/course/304x171/1354196_6a7e.jpg",
			"locale": {
				"locale": "en_US",
				"_class": "locale",
				"title": "English (US)",
				"english_title": "English (US)"
			},
			"has_closed_caption": true,
			"instructional_level": "Beginner Level",
			"instructional_level_simple": "Beginner",
			"content_length_practice_test_questions": 0,
			"is_user_subscribed": false,
			"buyable_object_type": "course",
			"published_time": "2017-09-20T20:55:32Z",
			"objectives_summary": [
				"Build a \"Legend of Zenda\" game in Unity3D from scratch.",
				"Navigate the Unity and Blender interfaces",
				"Build 3D models for the game in Blender."
			],
			"bestseller_badge_content": null,
			"free_course_subscribe_url": null,
			"is_recently_published": true,
			"preview_url": "/1354196/preview/",
			"predictive_score": null,
			"relevancy_score": null,
			"input_features": null,
			"lecture_search_result": null,
			"discount": null,
			"price": "A$205",
			"content_info": "40.5 hours"
		}
	],
	category: [
		{
			name: "Development",
			path: "/development",
			subcategory: [
				{
					name: "web development",
					path: "/webdevelopment",
				}, {
					name: "mobile apps",
					path: "/mobileapps",
				}
			]
		}, {
			name: "business",
			path: "/business"
		}, {
			name: "IT & Software",
			path: "/itsoftware",
			subcategory: [
				{
					name: "IT certification",
					path: "/ITcertification",
				}, {
					name: "Networks & Security",
					path: "/networkssecurity",
					subcategory: [
						{
							name: "hardware",
							path: "/hardware"
						}, {
							name: "software",
							path: "/software"
						}
					]
				}
			]
		},
	]
}

function dataList(state = initialUserState, action) {
	switch (action.type) {
		case "LOAD_DATA":
			return {
				...state,
				data: action.data
			};
		case "LOAD_CATEGORIES":
			return {
				...state,
				category: action.category
			};
		case "CLEAN_DATA":
			return initialUserState;
		default:
			return state
	}
}

export default dataList