const pagePath = {
	Home: '/',
	SingleCourse: '/course',
	Author: '/author',
	Categories: '/categories',
	Category: '/category',
	Help:'/help',
	Inbox: '/inbox',
	ViewPublicProfile: '/viewpublicprofile',    
	Profile: '/profile',
	Photo:'/photo',
	MyCourses: '/mycourses',
	WishList: '/wishlist',
	Account: '/account',
	Setting:'/setting',
	DeleteAccount:'/deleteacount',
	PurchaseHistory:'/purchasehistory',
	ShoppingCart:'/shoppingcart',
	Notification:'/notification',
	InstructorDashboard:'/instructordashboard',
	AddNewCourse: '/addnewcourse',
	EditCourse: '/editcourse',
	EditCourseGoal:'/goals',
	EditCoursePractice:'/practice',
	EditCourseLanding:'/landing',
	EditCoursePrice:'/price',
	EditCourseMessage:'/Message',
	
	ChangePassword: '/change-password',
	Logout: '/logout',
};

export default pagePath;