const pagePath = {
    Home: "/",
    Mycourse:"/mycourse",
    SingleCourse: "/course",
    Author: "/author",
    Account:"/account",
    Message:"/message",
    Settings:"/settings",
    Category: "/category",
    Course: "/course",
    Help:"/help",
    Wallet:"/wallet",
    Inbox: "/inbox",
    ViewPublicProfile: "/viewpublicprofile",    
    Profile: "/profile",
    MyCourses: "/mycourses",
    Account: "/account",
    Payment:"/payment",
    Preference:"/preference",
    MyCart: "/mycart",
    PaymentAndOrder:"/paymentorder",
    Settings:"/settings",
    Help:"/help",
    PurchaseHistory:"/purchasehistory",
    ShoppingCart:"/shoppingcart",
    Notification:"/notification",
    InstructorDashboard:"/instructordashboard",
    ResetPassword: "/resetpassword",
};

export default pagePath;