import LocalizedString from 'react-localization';

const string = new LocalizedString({
    en:{
        MenuLoginSignup: "Login/Signup",
        LoginDialogHeader: "Login with your email",
        ErrorDialogHeader: "Error",
        ForgotPasswordDialogHeader: "Forgot password ?",
        UnknownDialogHeader: "Unknown",
        LoginWithGoogle: "Continue with Google",
        LoginWithFacebook: "Continue with Facebook",
        Email: "Your email",
        Password: "Password",
        ConfirmPassword: "Retype your password here.",
        ForgotPassword: "Forgot Password?",
        EnterEmailToResetPassword:"Enter your Email address to reset your password",
        Submit: "Submit",
        Login: "Login",
        Signup: "Sign up",
        ResetPassword: "Reset Password",
        MenuCategory:"Cateogories",
        MenuBeAnInstructor:"Be an Instructor",
        CreateCourseTitle: "Create a New Course",
        CreateCourseContent: "ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        CreateNewCourse: "Create New Course",
        Messages:"Messages",
        Settings:"Settings",
        Help:"Help",
        Wallet:"Wallet",
        Mycourse:"My Courses",
        Notification: "Notifications",
        PurchaseHistory:"Purchase History",
        InstructorDashboard: "Instructor Dashboard",
        LogOut:"Log Out",
        Back: "Back",
        Of: "of",
        Off: "Off",
        Day: "day",
        Days: "days",
        Hours: "hours",
        minutes: "minutes",
        LeftAtThisPrice: " left at this price!",
        BuyNow: "Buy Now",
        AddToCart: "Add to Cart",
        Includes: "Includes",
        OnDemandVideo: "on-demand videoes",
        SupplementalResources: "supplemental resources",
        FullLifetimeAccess: "full lifetime Access",
        AccessonmobileandTV: "Access on mobile and TV",
        StudentsEnrolled: "students enrolled",
        CreateBy: "created by",
        LastUpdated: "Last Updated",
        PagesInTotal: "pages in total",
        InitializingApp: " Initializing App ...",
        ErrorNotAbleToInitApp: "Unable to initialize the app.",
        ErrorNotAbleToLoadLocation: "Unable to load location from server.",
        ErrorNotAbleToLoadCourse:"Unable to load course from server.",
        ErrorNotAbleToLoadCategory:"Unable to load category from server.",
        ErrorNotAbleToLoadSearchOptions: "Unable to load search options from server.",
        ErrorNotAbleToLogin: "Unable to Login",
        SearchEnterKeyWord:"Enter a keywork. etc. Math, English."
    },
    it: {
    }
});

export default string;