import LocalizedString from 'react-localization';

const string = new LocalizedString({
    en:{
        MenuLoginSignup: "Login/Signup",
        LoginDialogHeader: "Login with your email",
        ErrorDialogHeader: "Error",
        ForgotPasswordDialogHeader: "Forgot password ?",
        UnknownDialogHeader: "Unknown",
        LoginWithGoogle: "Continue with Google",
        LoginWithFacebook: "Continue with Facebook",
        FirstName: "First name",
        LastName: "Last name",
        Email: "Your email",
        Password: "Password",
        ConfirmPassword: "Retype your password here.",
        ForgotPassword: "Forgot Password?",
        EnterEmailToResetPassword:"Enter your Email address to reset your password",
        Submit: "Submit",
        Login: "Login",
        Signup: "Sign up",
        SignupStudentAccount: "Sign up as a student",
        SignupInstructorAccount: "Sign up as a instructor",
        Inbox: "Inbox",
        MyCourses: "My Courses",
        MyCart: "My Cart",
        PaymentAndOrder: "Payment & Order",
        Settings: "Settings",
        ResetPassword: "Reset Password",
        MenuCategory:"Cateogories",
        MenuBeAnInstructor:"Be an Instructor",
        CreateCourseTitle: "Create a New Course",
        CreateCourseContent: "ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco",
        CreateNewCourse: "Create New Course",
        Messages:"Messages",
        Settings:"Settings",
        Help:"Help",
        Wallet:"Wallet",
        Mycourse:"My Courses",
        Notification: "Notifications",
        PurchaseHistory:"Purchase History",
        InstructorDashboard: "Instructor Dashboard",
        LogOut:"Log Out",
        Back: "Back",
        Of: "of",
        Off: "Off",
        Day: "day",
        Days: "days",
        Hours: "hours",
        minutes: "minutes",
        LeftAtThisPrice: " left at this price!",
        BuyNow: "Buy Now",
        AddToCart: "Add to Cart",
        Includes: "Includes",
        OnDemandVideo: "on-demand videoes",
        SupplementalResources: "supplemental resources",
        FullLifetimeAccess: "full lifetime Access",
        AccessonmobileandTV: "Access on mobile and TV",
        StudentsEnrolled: "students enrolled",
        EmailSentToRecoverPassword: "An e-mail containing a link to recover your password has been sent to your email address",
        CreateBy: "created by",
        LastUpdated: "Last Updated",
        PagesInTotal: "pages in total",
        InitializingApp: " Initializing App ...",
        ErrorNotAbleToInitApp: "Unable to initialize the app.",
        ErrorNotAbleToLoadLocation: "Unable to load location from server.",
        ErrorNotAbleToLoadCourse:"Unable to load course from server.",
        ErrorNotAbleToLoadCategory:"Unable to load category from server.",
        ErrorNotAbleToLoadSearchOptions: "Unable to load search options from server.",
        ErrorNotAbleToLogin: "Unable to Login",
        ErrorNotAbleToSignup: "Unable to Sign up", 
        ErrorUnknown: "Unknow error occured",        
        NoFirstName : "Please key in your first name",
        NoLastName: " please key in your last name",
        ErrorNameFormat: 'name can contain alphabets only',
        NoEmail: "Email address shouldn't be empty",
        InvalidEmail: "Your email format is wrong.",
        NoPassword: "Password field shouldn't be empty",
        InvalidPassword: "Your password format is wrong, it should be at least 8 characters long containing number and alphabetic letter",
        NoConfirmPassword: "please retype your password here",
        InvalidConfirmPassword: "The two passwords you entered does not match",
        InvalidRecaptcha: "If you are not a robot, tick the box or complete the challenge",
        SearchEnterKeyWord:"Enter a keywork. etc. Math, English.",
        YouAreAlreadyLoggedIn: "You are already logged in",
        AccountViewPublicProfile: "View public Profile",
        AccountMyCourses: "My Courses",
        AccountProfile: "Profile",
        AccountAccount: "Account",
        AccountPayment: "Payment",
        AccountPreference: "Preference"
    },
    it: {
    }
});

export default string;